### ISSUE TITLE
Deploying a script using Travis CI on a remote server.

### ISSUE THREAD

**Issue by kiranshashiny** [steveklabnik/automatically_update_github_pages_with_travis_example#11]
I have a requirement where I have to remotely deploy the GH content, and then execute an app at the remote server, at the end of the "after_success".
The deploying of the GH works - so does launching the APP on the remote server.
The problem is when I deploy this in deploy.sh as shown - theTravis  build fails as seen on the console.
However the launch of the app is successful on the remote server and everything looks OK - except for this Travis CI build that shows up as failed !

deploy.sh
  cut and paste
npm install somepackage.tgz
echo "Done installing package"
echo "Starting the app "
nohup node  app.js  &   <<<<<<<<<  This launches - except that Travis CI is waiting for it to finish
echo " Finished starting app"

**Comment by steveklabnik** [comment]
I would suggest filing a bug with Travis support.
