### ISSUE TITLE
gh-pages 404

### ISSUE THREAD

**Issue by cruikshj** [steveklabnik/automatically_update_github_pages_with_travis_example#7]
This process does indeed successfully commit changes and push to the gh-pages branch as expected, however it seems to cause a problem with the hosting of the site.  After changes are pushed using this method, the pages site responds with 404. There are no problems with the gh-pages files as far as I can tell.

Here is my project: https://github.com/shaftware/cmdrjs

Any suggestions?

**Comment by steveklabnik** [comment]
http://shaftware.github.io/cmdrjs/ loads for me. How are you seeing a 404?

**Comment by cruikshj** [comment]
Ah interesting... I should have checked that...  however, it what no longer loads is www.cmdrjs.com.  So it must be something with the CNAME file?

**Comment by cruikshj** [comment]
Haha... I am silly....  typoed the cname in the echo command.  Thanks for looking so fast.

**Comment by steveklabnik** [comment]
Great! Glad it's working. DNS: it always gives me trouble.

**Comment by cruikshj** [comment]
Thanks for this example btw... I am a bit of a github noob.

**Comment by steveklabnik** [comment]
You're very welcome :)
